#!/bin/sh
#

MOUNT="/media/DISK_A1/system"
INITD="$MOUNT/etc/init.d"
BIN="$MOUNT/usr/bin/sd-idle-2.6"
TIMEDOWN="-i 600"
SLEEP="-c 30"

export LANG=C
export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib

start() {
	$BIN $TIMEDOWN $SLEEP
}

stop() {
	killall -15 sd-idle-2.6 2>/dev/null
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
    *)
		echo "Usage: $0 {start|stop}"
		;;
esac
