#!/bin/sh
# Copyright (C) 2011 OpenWrt.org

MOUNTPNT="/media/DISK_A1"
MOUNT="$MOUNTPNT/system"

export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib

start() {
	$MOUNT/usr/sbin/unfsd -e /media/DISK_A1/system/etc/exports2 -n 2049 -m 1058 &
}

stop() {
	killall -15 unfsd 2> /dev/null
}

case "$1" in
	start)
	    start
	    ;;
	stop)
	    stop
	    ;;
	restart)
	    stop
	    sleep 1
	    start
	    ;;
	*)
	    echo "Usage: $0 {start|stop|restart}"
	    ;;
esac

