#!/bin/sh

MOUNTPNT="/media/DISK_A1"
SYSTEM="$MOUNTPNT/system"
UMURMURD="$SYSTEM/usr/bin/umurmurd"
CONFIG="$SYSTEM/etc/umurmur/umurmur.conf"
PIDF="$SYSTEM/var/run/umurmurd.pid"
PORT=`cat $CONFIG | grep bindport | sed 's/bindport = //g' | sed 's/;//g'`

start() {
	$UMURMURD -c "$CONFIG" -p "$PIDF"
	iptables -I INPUT -p tcp --dport $PORT -j ACCEPT
	iptables -I INPUT -p udp --dport $PORT -j ACCEPT
}

stop() {
	kill `cat "$PIDF"`
	iptables -D INPUT -p tcp --dport $PORT -j ACCEPT
	iptables -D INPUT -p udp --dport $PORT -j ACCEPT
}

case "$1" in
	start)
	    start
	    ;;
	stop)
	    stop
	    ;;
	restart)
	    stop
	    start
	    ;;
    link_up)
        ;;
    ppp_up)
        ;;
    link_down)
        ;;
    ppp_down)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|link_up|link_down|ppp_up|ppp_down}"
        ;; 
esac
