#!/bin/sh
MOUNT="/media/DISK_A1/system"
export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib

NAME="Polipo"
PIDFILE="$MOUNT/var/run/polipo.pid"
POLIPO="$MOUNT/usr/sbin/polipo"
CONFIG_FILE="$MOUNT/etc/polipo/config"
LOGFILE="$MOUNT/var/log/polipo.log"



start()
{
	echo "Starting $NAME... "
    rm $PIDFILE
    $POLIPO -c $CONFIG_FILE pidFile=$PIDFILE logFile=$LOGFILE
}

stop()
{
	echo "Shutting down $NAME... "
	[ -f ${PIDFILE} ] && kill `cat ${PIDFILE}`
}
        
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 (start|stop|restart)"
		;;
esac
