#!/bin/sh
# Copyright (C) 2006-2011 OpenWrt.org

MOUNT="/media/DISK_A1/system"
export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib

NAME="Privoxy"
PIDFILE="$MOUNT/var/run/privoxy.pid"
PRIVOXY="$MOUNT/usr/sbin/privoxy"
CONFIG_FILE="$MOUNT/etc/privoxy/config"


SERVICE_USE_PID=1

start() {
        echo "Starting $NAME... "
        $PRIVOXY --pidfile $PIDFILE $CONFIG_FILE
        iptables -t nat -A PREROUTING -i br0 -p tcp --dport 80 -j REDIRECT --to-port 3128  ! -d 192.168.0.0/16
}

stop() {
        echo "Killing $NAME... "
        iptables -t nat -D PREROUTING -i br0 -p tcp --dport 80 -j REDIRECT --to-port 3128  ! -d 192.168.0.0/16
        killall privoxy
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                sleep 1
                start
                ;;
        *)
                echo "Usage: $0 (start|stop|restart)"
                ;;
esac

