#!/bin/sh

MOUNT="/media/DISK_A1/system"
export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib


NGINX_BIN=$MOUNT/usr/sbin/nginx


start() {
	$NGINX_BIN
}

stop() {
	$NGINX_BIN -s stop
}

reload() {
	$NGINX_BIN -s reload
}

shutdown() {
	$NGINX_BIN -s quit
}


case $1 in
	start)
	start
	;;
	stop)
	shutdown
	;;
	restart)
	shutdown
        sleep 1
	start
	;;
	reload)
        reload
	;;
	link_up)
	;;
	ppp_up)
	;;
	link_down)
	;;
	ppp_down)
	;;
	*)
	echo "Usage: $0 {start|stop|restart|reload|link_up|link_down|ppp_up|ppp_down}"
	;;
esac
