#!/bin/sh

MOUNT="/media/DISK_A1/system"

export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib


start() {
	PIDPL=`screen -list | grep pyload | cut -f1 -d.`
	if [  -z "$PIDPL" ]; then
		cd $MOUNT/usr/share/pyload
		screen -dmS pyload python pyLoadCore.py
        fi
}

stop() {
	PIDPL=`screen -list | grep pyload | cut -f1 -d.`
	if [ ! -z "$PIDPL" ]; then
		kill $PIDPL
        fi
}

status() {
	PIDPL=`screen -list | grep pyload | cut -f1 -d.`
	if [ ! -z "$PIDPL" ]; then
		echo "pyLoad is running"
	else
		echo "pyLoad is not running"
        fi
}
        

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status
		;;
	restart)
		stop
		sleep 2
		start
		;;
	link_up)
		;;
	ppp_up)
		;;
	link_down)
		;;
	ppp_down)
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart|link_up|link_down|ppp_up|ppp_down}"
		;;
esac
