#!/bin/sh
#

MOUNT="/media/DISK_A1/system"
INITD="$MOUNT/etc/init.d"
BIN="$MOUNT/usr/bin/minidlna"
CONFIG="$MOUNT/etc/minidlna/minidlna.conf"
PIDFILE="$MOUNT/var/run/minidlna.pid"

export LANG=C
export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib

start() {
	$BIN -f $CONFIG -P $PIDFILE
}

stop() {
	if [ -e $PIDFILE ] ; then
	  kill -15 `cat $PIDFILE` 2>/dev/null
	else
	  killall -15 minidlna 2>/dev/null
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
    *)
		echo "Usage: $0 {start|stop}"
		;;
esac
