#!/bin/sh

MOUNT="/media/DISK_A1/system"
RP="$MOUNT/usr/sbin/vncrepeater"

export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib


start {
	$RP
	iptables -A INPUT -p tcp --dport 5500 -j ACCEPT
	iptables -A INPUT -p tcp --dport 5901 -j ACCEPT
}

stop() {
	killall vncrepeater
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 1
		start
		;;
	link_up)
		;;
	ppp_up)
		;;
	link_down)
		;;
	ppp_down)
		;;
	*)
		echo "Usage: $0 {start|stop|restart|link_up|link_down|ppp_up|ppp_down}"
		;;
esac
