#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

MOUNT="/media/DISK_A1/system"
export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib

export PHP_FCGI_CHILDREN=''
PORT=1026
BIN=$MOUNT/usr/bin/php-fcgi

start() {
	$BIN -b $PORT &
}

stop() {
	killall php-fcgi
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
		stop
		start
        ;;
    link_up)
        ;;
    ppp_up)
        ;;
    link_down)
        ;;
    ppp_down)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|link_up|link_down|ppp_up|ppp_down}"
        ;;
esac 


