#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

MOUNT="/media/DISK_A1/system"
export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/share/ptokax/cfg
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib:/usr/share/ptokax/cfg


PtokaX=$MOUNT/usr/bin/PtokaX

start() {
	$PtokaX -d -c $MOUNT/usr/share/ptokax
        iptables -A INPUT -p tcp --dport 411 -j ACCEPT
}

stop() {
	killall PtokaX
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
		stop
		start
       ;;
    *)
        echo "Usage: $0 {start|stop}"
        ;;
esac 


