#!/bin/sh

MOUNTPNT="/media/DISK_A1"
MOUNT="$MOUNTPNT/system"

export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib

start() {
	echo ""
	echo "Loading kernel modules:"
	insmod $MOUNT/lib/modules/2.6.22-tc/usbip_common_mod.ko
	insmod $MOUNT/lib/modules/2.6.22-tc/usbip.ko
	
	echo "Starting usbip daemon ...."
	$MOUNT/usr/bin/usbipd -D
	echo "Binding usb devices..."
# !!!! setup your usb devices here
#	$MOUNT/usr/bin/usbip_bind_driver --usbip <busid1>
#	$MOUNT/usr/bin/usbip_bind_driver --usbip <busid2>
}

stop() {
	echo ""
	echo "Unbinding usb devices...."
# !!!! setup your usb devices here
#	$MOUNT/usr/bin/usbip_bind_driver --other <busid1>
#	$MOUNT/usr/bin/usbip_bind_driver --other <busid2>
	echo -n "Killing usbip daemon...."
	killall usbipd
	sleep 1
	echo "Unloading kernel modules... "
	rmmod  usbip
	rmmod  usbip_common_mod
}

restart() {
	stop
	sleep 3
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	link_up)
		;;
	ppp_up)
		;;
	link_down)
		;;
	ppp_down)
		;;
	*)
		echo "Usage: $0 {start|stop|restart|link_up|link_down|ppp_up|ppp_down}"
		;;
esac
