#!/bin/sh
MOUNT="/media/DISK_A1/system"

export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib


case "$1" in
	start)
		echo "Starting aria2c daemon"
		umask 0000
		$MOUNT/usr/bin/aria2c --conf-path=$MOUNT/etc/aria2/aria2.conf
	;;
	stop)
		echo "Shutting down aria2c daemon"
		killall aria2c
	;;
	restart)
		killall aria2c
		sleep 1
		umask 0000
		$MOUNT/usr/bin/aria2c --conf-path=$MOUNT/etc/aria2/aria2.conf
	;;
	link_up)
	;;
	ppp_up)
	;;
	link_down)
	;;
	ppp_down)
	;;
	*)
		echo "Usage: $0 {start|stop|restart|link_up|link_down|ppp_up|ppp_down}"
	;;
esac
