#!/bin/sh
 
MOUNTPNT="/media/DISK_A1"
MOUNT="$MOUNTPNT/system"

CRON="$MOUNT/usr/sbin/crond"

export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib

start() {
	$CRON -L /dev/null
}

 stop() {
	killall crond
}

 case "$1" in
	start)
	    start
	    ;;
	stop)
	    stop
	    ;;
	restart)
	    stop
	    start
	    ;;
	*)
	    echo "Usage: $0 {start|stop}"
	    ;;
esac
