#!/bin/sh

START=70

MOUNTPNT="/media/DISK_A1"
MOUNT="$MOUNTPNT/system"
MAXCONS="7"
CONFIGFILE="$MOUNT/etc/netatalk/afpd.conf"
PIDFILE="$MOUNT/var/run/afpd.pid"

AFPD="$MOUNT/usr/sbin/afpd"
CNID="$MOUNT/usr/sbin/cnid_metad"

export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib


start()
{
	$CNID
	$AFPD -F ${CONFIGFILE} -P ${PIDFILE} -c ${MAXCONS}
}

stop()
{
	kill `cat "${PIDFILE}"`
	killall cnid_metad
}

reload()
{
	kill -s HUP `cat "${PIDFILE}"`
}

case "$1" in
	start)
	    start
	    ;;
	stop)
	    stop
	    ;;
	reload)
	    reload
	    ;;
	restart)
	    stop
	    start
	    ;;
	*)
	    echo "Usage: $0 {start|stop|reload|restart}"
	    ;;
esac
