#!/bin/sh
# Copyright (C) 2011 NDM Systems, McMCC

MOUNT="/media/DISK_A1/system"
INITD="$MOUNT/etc/init.d"
BIN="$MOUNT/usr/bin/mysqld"
CONFIG="--defaults-file=$MOUNT/etc/my.cnf"

export LANG=C
export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib

start() {
	$BIN $CONFIG &
}

stop() {
	killall -15 mysqld
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 3
		start
		;;
    *)
		echo "Usage: $0 {start|stop||restart}"
		;;
esac
