#!/bin/sh

MOUNT="/media/DISK_A1/system"
TRNEXE="$MOUNT/usr/bin/transmission-daemon"
TRNVAR="$MOUNT/var/transmission"
TRNPID="$TRNVAR/transmission.pid"
TRN_PORT=52400
TRN_RPC_PORT=9091 
export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib
export TRANSMISSION_WEB_HOME="$MOUNT/usr/share/transmission/web"

daemon_status ()
{
    [ -f $TRNPID ] && [ -d /proc/`cat $TRNPID` ]
}

start_daemon ()
{
	$TRNEXE -et -g $TRNVAR -x $TRNPID
	counter=5
    while [ $counter -gt 0 ]
    do
        daemon_status && break
        let counter=counter-1
        sleep 1
    done
#	iptables -A INPUT -p tcp --dport $TRN_PORT -j ACCEPT
#	iptables -A INPUT -p udp --dport $TRN_PORT -j ACCEPT
#	iptables -A INPUT -p tcp --dport $TRN_RPC_PORT -j ACCEPT
#?????? iptables -I INPUT -i lo -j ACCEPT ???????
}

stop_daemon ()
{
    # Kill transmission.
    kill `cat $TRNPID`
    # Wait until transmission is really dead (may take some time).
    counter=160
    while [ $counter -gt 0 ] 
    do
        daemon_status || break
        let counter=counter-1
		if [ counter = 1 ]; then
			killall -9 transmission-daemon 2> /dev/null
		fi
        sleep 1
    done
#	iptables -D INPUT -p tcp --dport $TRN_PORT -j ACCEPT 2> /dev/null
#	iptables -D INPUT -p udp --dport $TRN_PORT -j ACCEPT 2> /dev/null
#	iptables -D INPUT -p tcp --dport $TRN_RPC_PORT -j ACCEPT 2> /dev/null
#?????? iptables -D INPUT -i lo -j ACCEPT ???????
}

reload_daemon ()
{
    kill -HUP `cat $TRNPID`
}

case $1 in
    start)
        if daemon_status
        then
            echo Transmission daemon already running
        else
            echo Starting Transmission daemon...
            start_daemon
        fi
        ;;
    stop)
        echo Stopping Transmission daemon...
		stop_daemon
        ;;
    restart)
		stop_daemon
		start_daemon
        ;;
    reload)
		reload_daemon
        ;;
    status)
        if daemon_status
        then
            echo Running
        else
            echo Not running
        fi
        ;;
    settings)
	$TRNEXE -et -g $TRNVAR -d
	;;
    link_up)
        ;;
    ppp_up)
        ;;
    link_down)
        ;;
    ppp_down)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status|settings|link_up|link_down|ppp_up|ppp_down}"
        ;;
esac
