#!/bin/sh

MOUNT="/media/DISK_A1/system"
IBIN="$MOUNT/usr/sbin/inadyn"
ICONFIG="$MOUNT/etc/inadyn.conf"
ILOG="$MOUNT/var/inadyn.log"
IPID="$MOUNT/var/inadyn.pid"

export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib

daemon_status ()
{
	[ -f $IPID ] && [ -d /proc/`cat $IPID` ]
}

start_daemon() {
	$IBIN -F $ICONFIG -L $ILOG -P $IPID -V 0 -b
}

stop_daemon() {
	kill `cat $IPID`
}

case "$1" in
	start)
		if daemon_status
		then
			echo inadyn already running
		else
			start_daemon
		fi
		;;
	stop)
		stop_daemon
		;;
	restart)
		stop_daemon
		sleep 1
		start_daemon
		;;
	status)
		if daemon_status
		then
			echo Running
		else
		echo Not running
		fi
		;;
	link_up)
		;;
	ppp_up)
		;;
	link_down)
		;;
	ppp_down)
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status|link_up|link_down|ppp_up|ppp_down}"
		;;
esac
