#!/bin/sh

MOUNT="/media/DISK_A1/system"
BIN="$MOUNT/usr/bin/3proxy"
CONFIG="$MOUNT/etc/3proxy/3proxy.conf"

export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib

start_daemon() {
	$BIN  $CONFIG &
}

stop_daemon() {
	killall 3proxy
}

case "$1" in
	start)
		start_daemon
		;;
	stop)
		stop_daemon
		;;
	restart)
		stop_daemon
		start_daemon
		;;
	link_up)
		;;
	ppp_up)
		;;
	link_down)
		;;
	ppp_down)
		;;
	*)
		echo "Usage: $0 {start|stop|restart|link_up|link_down|ppp_up|ppp_down}"
		;;
esac
