#!/bin/sh

MOUNT="/media/DISK_A1/system"
XBIN="$MOUNT/usr/sbin/xinetd"
XCONFIG="$MOUNT/etc/xinetd.conf"
XPID="$MOUNT/var/xinetd.pid"

export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib

daemon_status ()
{
	[ -f $XPID ] && [ -d /proc/`cat $XPID` ]
}

start_daemon() {
	$XBIN -syslog daemon -stayalive -f $XCONFIG -pidfile $XPID
}

stop_daemon() {
	kill `cat $XPID`
}

reload_daemon() {
	kill -HUP `cat $XPID`
}

case "$1" in
	start)
		if daemon_status
		then
			echo xinetd already running
		else
			start_daemon
		fi
		;;
	stop)
		stop_daemon
		;;
	restart)
		stop_daemon
		sleep 1
		start_daemon
		;;
	reload)
		reload_daemon
		;;
	status)
		if daemon_status
		then
			echo Running
		else
		echo Not running
		fi
		;;
	link_up)
		;;
	ppp_up)
		;;
	link_down)
		;;
	ppp_down)
		;;
	*)
		echo "Usage: $0 {start|stop|reload|restart|status|link_up|link_down|ppp_up|ppp_down}"
		;;
esac
