#!/bin/sh

MOUNTPNT="/media/DISK_A1"
MOUNT="$MOUNTPNT/system"
ZNC="$MOUNT/usr/bin/znc"

export PATH=$MOUNT/bin:$MOUNT/sbin:$MOUNT/usr/bin:$MOUNT/usr/sbin:/sbin:/usr/sbin:/bin:/usr/bin
export LD_LIBRARY_PATH=$MOUNT/lib:$MOUNT/usr/lib:/lib:/usr/lib

start() {
    # NB: no chpst in standard busybox
    # FIXME: 99 == nobody
    # FIXME: problems with znc native background mode -- logging problems?
    chpst -u 99 $ZNC -d $MOUNT/etc/znc -D >/dev/null 2>&1 &
    # NB: 7000 is port from config
    iptables -A INPUT -p tcp --dport 7000 -j ACCEPT
}

stop() {
    iptables -D INPUT -p tcp --dport 7000 -j ACCEPT
    killall znc
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;; 
esac

